# Generated by Django 2.0 on 2018-05-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('qtyDamage', models.IntegerField(blank=True, default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('employeeId', models.IntegerField(blank=True, default=0)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('locationId', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default=None, max_length=30)),
                ('lastName', models.CharField(default=None, max_length=30)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('vendorId', models.IntegerField(blank=True, default=0)),
                ('employeeId', models.IntegerField(blank=True, default=0)),
                ('tax', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingTransactionItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionId', models.IntegerField(blank=True, default=0)),
                ('quantityBought', models.IntegerField(blank=True, default=0)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('purchasedprice', models.FloatField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('inStockQty', models.IntegerField(blank=True, default=0)),
                ('picture', models.CharField(default=None, max_length=30)),
                ('color', models.CharField(default=None, max_length=30)),
                ('ageRequirement', models.CharField(default=None, max_length=30)),
                ('purchasedPrice', models.FloatField(blank=True, default=None, null=True)),
                ('salePrice', models.FloatField(blank=True, default=None, null=True)),
                ('department', models.CharField(default=None, max_length=30)),
                ('vendorId', models.IntegerField(blank=True, default=0)),
                ('locationId', models.IntegerField(blank=True, default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=30)),
                ('storeId', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField(blank=True, default=0)),
                ('itemId', models.IntegerField(blank=True, default=0)),
                ('locationQty', models.IntegerField(blank=True, default=0)),
                ('employeeId', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('storeId', models.IntegerField(blank=True, default=0)),
                ('employeeId', models.IntegerField(blank=True, default=0)),
                ('tax', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingTransactionItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionId', models.IntegerField(blank=True, default=0)),
                ('quantitySold', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=50)),
                ('hoursOpen', models.CharField(default=None, max_length=150)),
                ('phoneNumber', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(default=None, max_length=30)),
                ('hoursOpen', models.CharField(default=None, max_length=150)),
            ],
        ),
    ]
