# Generated by Django 2.0 on 2018-05-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingtransactionitem',
            old_name='purchasedprice',
            new_name='purchasedPrice',
        ),
        migrations.AlterModelTable(
            name='damageitem',
            table='damage_item',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='incomingtransaction',
            table='incoming_transaction',
        ),
        migrations.AlterModelTable(
            name='incomingtransactionitem',
            table='incoming_transaction_item',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='locationitem',
            table='LocationItem',
        ),
        migrations.AlterModelTable(
            name='outgoingtransaction',
            table='outgoing_transaction',
        ),
        migrations.AlterModelTable(
            name='outgoingtransactionitem',
            table='outgoing_transaction_item',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
