# Generated by Django 2.0 on 2018-06-28 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180517_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damageitem',
            name='employeeId',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='employeeId',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='employeeId',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='employeeId',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
