# Generated by Django 2.0 on 2018-06-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180628_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phoneNumber',
        ),
    ]
