# Generated by Django 2.0 on 2018-07-06 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_employee_phonenumber'),
    ]

    operations = [
    
    ]
