# Generated by Django 2.0 on 2018-06-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180628_0816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
