# Generated by Django 2.0 on 2018-07-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180706_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchasedPrice',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='salePrice',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
