# Generated by Django 2.0 on 2018-07-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180706_2314'),
    ]

    operations = [
        
    ]
