# Generated by Django 2.0 on 2018-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180708_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='subtotal',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
