# Generated by Django 2.0 on 2018-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_outgoingtransaction_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='total',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
