# Generated by Django 2.0 on 2018-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180708_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='employeeId',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
