# Generated by Django 2.0 on 2018-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180708_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='subtotal',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
