# Generated by Django 2.0 on 2018-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180708_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='tax',
            field=models.FloatField(blank=True, default=0.0925, null=True),
        ),
    ]
