# Generated by Django 2.0 on 2018-07-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20180716_0219'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='incomingtransaction',
        #     name='subtotal',
        #     field=models.FloatField(blank=True, default=None),
        # ),
        # migrations.AddField(
        #     model_name='incomingtransaction',
        #     name='total',
        #     field=models.FloatField(blank=True, default=None),
        # ),
        # migrations.AddField(
        #     model_name='item',
        #     name='barcode',
        #     field=models.CharField(default=None, max_length=30, unique=True),
        # ),
        # migrations.AlterModelTable(
        #     name='employee',
        #     table=None,
        # ),
    ]
