# Generated by Django 2.0 on 2018-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_damageitem_description'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='incomingtransactionitem',
        #     name='transactionId',
        # ),
        # migrations.RemoveField(
        #     model_name='outgoingtransactionitem',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='outgoingtransactionitem',
        #     name='itemId',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.DeleteModel(
        #     name='IncomingTransactionItem',
        # ),
    ]
