# Generated by Django 2.0 on 2018-09-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20180902_2234'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='outgoingtransactionitem',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=12345, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='outgoingtransactionitem',
        #     name='itemId',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
    ]
