# Generated by Django 2.0 on 2018-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20180902_2241'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='incomingtransactionitem',
        #     name='transactionId',
        # ),
        migrations.AlterField(
            model_name='outgoingtransactionitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='IncomingTransactionItem',
        ),
    ]
