# Generated by Django 2.0 on 2018-09-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20180902_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransactionitem',
            name='itemId',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
