# Generated by Django 2.0 on 2018-09-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20180925_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingtransactionitem',
            old_name='itemId',
            new_name='barcode',
        ),
    ]
