# Generated by Django 2.0 on 2018-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20180925_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingtransactionitem',
            name='barcode',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
