# Generated by Django 2.0 on 2018-09-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20180925_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default=None, max_length=30)),
                ('transactionId', models.IntegerField(blank=True, default=0)),
                ('quantityBought', models.IntegerField(blank=True, default=0)),
                ('purchasedPrice', models.FloatField(blank=True, default=None, null=True)),
                ('tax', models.FloatField(blank=True, default=0.0925, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incoming_transaction_item',
            },
        ),
    ]
